<style type="text/css">
.breadcrumb > li + li:before {
    color: #CCCCCC;
    content: ">";
    padding: 0 5px;
}
.breadcrumb a{
    font-size: 19px;
}
h1{
    margin-top: 56px;
}
.gongsi{
    padding-bottom: 20px;
    border-bottom: 1px solid black;
}
.gongsi .tab-content{
    margin-left: 30px;
}
</style>
<ol class="breadcrumb">
    <li>
        <a href="#">首页</a>
    </li>
    <li>
        <a href="#" >行业招聘</a>
    </li>
     <li>
        <a href="#" class="active">企业信息</a>
    </li>
</ol>
<h1 class="text-center">科技公司</h1>
<div >
    <div class="gongsi">
        <ul class="nav nav-tabs " role="tablist" id="myTab">
            <li class="active">
                <a href="#home" role="tab" data-toggle="tab">公司简介</a>
            </li>
            <li >
                <a href="#home" role="tab" data-toggle="tab">招聘职位</a>
            </li>
        </ul>
        <div class="tab-content">

           &nbsp; 
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">3V</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">生物青岛研发中心、潍坊研发中心特面向海内外招聘高级英才！</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><?xml:namespace prefix = o ns = "urn:schemas-microsoft-com:office:office" /><o:p></o:p></SPAN></P>
<P><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">招聘职位：</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">一、体外诊断试剂研发人员</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">、专业：生物、化学、医学、制药、临床检验等专业。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">、学历：本科、硕士、博士、博士后、海归人员。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">、从业背景：</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black">①</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">专业基础扎实、</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">3</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">年以上实验室工作经验。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black">②</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">有体外诊断试剂研发经验者优先。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">二、资深免疫诊断试剂研发工程师</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">、专业：生物、化学、医学、制药、临床检验等专业。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">、学历：本科、硕士、博士、博士后、海归人员。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">、从业背景：</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black">①</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">扎实的免疫学或检验医学方面的理论和实践知识，有独立解决问题之能力。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black">②</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">在化学发光、时间分辨、酶免、金标、胶乳比浊技术领域造诣深厚，熟悉相关技术及工艺流程</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">;<o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black">③</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">精通国际前沿诊断技术，把握国内外诊断技术发展动态；</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black">④</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">有领导团队开展工作的经验和能力。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">三、资深</SPAN><SUP><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">14</SPAN></SUP><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">C/<SUP>13</SUP>C/<SUP>18</SUP>F</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">等体内核药物研发工程师</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">、专业：生物、化学、医学、制药、临床检验等专业。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">、学历：本科、硕士、博士、博士后、海归人员。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">、从业背景：熟悉</SPAN><?xml:namespace prefix = st1 ns = "urn:schemas-microsoft-com:office:smarttags" /><st1:chmetcnv w:st="on" UnitName="C" SourceValue="14" HasSpace="False" Negative="False" NumberType="1" TCSC="0"><SUP><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">14</SPAN></SUP><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">C</SPAN></st1:chmetcnv><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">/<st1:chmetcnv w:st="on" UnitName="C" SourceValue="13" HasSpace="False" Negative="False" NumberType="1" TCSC="0"><SUP>13</SUP>C</st1:chmetcnv>/<st1:chmetcnv w:st="on" UnitName="F" SourceValue="18" HasSpace="False" Negative="False" NumberType="1" TCSC="0"><SUP>18</SUP>F</st1:chmetcnv></SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">等体内核药物相关技术和工艺流程，良好的从业经历和团队领导能力。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">四、胶乳试剂研发工程师</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">、专业：材料科学、纳米科学、高分子材料、有机化学等相关专业。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">、学历：本科、硕士、博士、博士后、海归人员。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">、从业背景：</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black">①</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">熟悉纳米胶乳颗粒的制备工艺及流程；</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black">②</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">具有胶乳增强免疫比浊试剂研发经验或从事过相关课题的研究。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">五、血糖类试纸研发工程师</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">、专业：分析化学、临床化学、电化学、生物感测技术等相关专业。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">、学历：本科、硕士、博士、博士后、海归人员。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">、从业背景：</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black">①</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">深厚的电化学理论及实验基础</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black">②</SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">有干化学试纸研发和工作经验者优先考虑。</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">六、业务员</SPAN><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial"><o:p></o:p></SPAN></P>
<P><SPAN lang=EN-US style="FONT-SIZE: 9pt; COLOR: black; FONT-FAMILY: &#718;&#805;,Verdana,Arial">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">本科，生物、化学、医学、制药、临床检验等专业。或有诊断试剂营销经验。主要职责是拓展和维护市场。</SPAN></P>
<P><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">联系人:王主任&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 电话:0536-8889093&nbsp;&nbsp; 13793600529</SPAN></P>
<P><SPAN style="FONT-SIZE: 9pt; COLOR: black; mso-ascii-font-family: '&#718;&#805;,Verdana,Arial'; mso-hansi-font-family: '&#718;&#805;,Verdana,Arial'">E-mail:office3V@yahoo.com.cn</SPAN></P>
        


        </div>
    </div>
</div>